@echo off
cd chrome\googlev8\Results
del *.csv
cd ..\..\..
cd chrome\install\Results
del *.csv
cd ..\..\..
cd chrome\kraken\Results
del *.csv
cd ..\..\..
cd chrome\spider\Results
del *.csv
cd ..\..\..
cd chrome\uninstall\Results
del *.csv
cd ..\..\..
cd firefox\googlev8\Results
del *.csv
cd ..\..\..
cd firefox\install\Results
del *.csv
cd ..\..\..
cd firefox\kraken\Results
del *.csv
cd ..\..\..
cd firefox\spider\Results
del *.csv
cd ..\..\..
cd firefox\uninstall\Results
del *.csv
cd ..\..\..
cd ie\googlev8\Results
del *.csv
cd ..\..\..
cd ie\kraken\Results
del *.csv
cd ..\..\..
cd ie\spider\Results
del *.csv
cd ..\..\..
cd office2010\excel\Results
del *.csv
cd ..\..\..
cd office2010\word\Results
del *.csv
cd ..\..\..
cd opera\googlev8\Results
del *.csv
cd ..\..\..
cd opera\install\Results
del *.csv
cd ..\..\..
cd opera\kraken\Results
del *.csv
cd ..\..\..
cd opera\spider\Results
del *.csv
cd ..\..\..
cd opera\uninstall\Results
del *.csv
cd ..\..\..
cd safari\googlev8\Results
del *.csv
cd ..\..\..
cd safari\install\Results
del *.csv
cd safari\kraken\Results
del *.csv
cd ..\..\..
cd safari\spider\Results
del *.csv
cd ..\..\..
cd safari\uninstall\Results
del *.csv
cd ..\..\..
cd acrobatReader\install\Results
del *.csv
cd ..\..\..
cd acrobatReader\uninstall\Results
del *.csv
cd ..\..\..
