@echo off
cd C:\cana\java\autoIT\chrome\googlev8\Results
del *.csv
cd C:\cana\java\autoIT\chrome\install\Results
del *.csv
cd C:\cana\java\autoIT\chrome\kraken\Results
del *.csv
cd C:\cana\java\autoIT\chrome\spider\Results
del *.csv
cd C:\cana\java\autoIT\chrome\uninstall\Results
del *.csv
cd C:\cana\java\autoIT\firefox\googlev8\Results
del *.csv
cd C:\cana\java\autoIT\firefox\install\Results
del *.csv
cd C:\cana\java\autoIT\firefox\kraken\Results
del *.csv
cd C:\cana\java\autoIT\firefox\spider\Results
del *.csv
cd C:\cana\java\autoIT\firefox\uninstall\Results
del *.csv
cd C:\cana\java\autoIT\ie\googlev8\Results
del *.csv
cd C:\cana\java\autoIT\ie\kraken\Results
del *.csv
cd C:\cana\java\autoIT\ie\spider\Results
del *.csv
cd C:\cana\java\autoIT\office2010\excel\Results
del *.csv
cd C:\cana\java\autoIT\office2010\word\Results
del *.csv
cd C:\cana\java\autoIT\opera\googlev8\Results
del *.csv
cd C:\cana\java\autoIT\opera\install\Results
del *.csv
cd C:\cana\java\autoIT\opera\kraken\Results
del *.csv
cd C:\cana\java\autoIT\opera\spider\Results
del *.csv
cd C:\cana\java\autoIT\opera\uninstall\Results
del *.csv
cd C:\cana\java\autoIT\safari\googlev8\Results
del *.csv
cd C:\cana\java\autoIT\safari\install\Results
del *.csv
cd C:\cana\java\autoIT\safari\kraken\Results
del *.csv
cd C:\cana\java\autoIT\safari\spider\Results
del *.csv
cd C:\cana\java\autoIT\safari\uninstall\Results
del *.csv
cd C:\cana\java\autoIT\acrobatReader\install\Results
del *.csv
cd C:\cana\java\autoIT\acrobatReader\uninstall\Results
del *.csv
