/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opbm_Opbm */

#ifndef _Included_opbm_Opbm
#define _Included_opbm_Opbm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opbm_Opbm
 * Method:    sendWindowToForeground_native
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_opbm_Opbm_sendWindowToForeground_1native
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
